//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bikes
    {
        public int Id { get; set; }
        public string Soket { get; set; }
        public string Years { get; set; }
        public string Firm { get; set; }
        public string Type { get; set; }
        public string Core { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public string ChtoEto { get; set; }
        public string Image { get; set; }
    }
}
